name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - env/staging

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          terraform apply -auto-approve -var "token=${{ secrets.TOKEN }}"
